### ISSUE TITLE
Currently ignoring FirestoreExceptions on user data provider refresh

### ISSUE THREAD

**Issue by lausan3** [GomikoApp/Gomiko#33]
We're currently ignoring any FirestoreExceptions whenever we refresh user data in the user data provider (at utils/providers/user_data_provider.dart), it's possible this will become tech debt in the future.

![image](https://github.com/GomikoApp/Gomiko/assets/92795688/955448d3-8637-4b17-be7b-7ec6add2b885)

**Comment by SLuo490** [comment]
Close issue as we no longer use refreshData(), used streamProvider() instead.
